# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  SonarToken: '554831c2d756d3aae0d1b3a09d634917d1aec8d5'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'java-project_java-project'
    projectName: 'java-project'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: SonarQubeAnalyze@5


- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: PowerShell@2
  displayName: QGcheck-with-UP
  inputs:
    targetType: 'inline'
    script: |
      $credPair = "admin:Devops@2448"
      
      # Step 2. Encode the pair to Base64 string
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credPair))
      
      # Step 3. Form the header and add the Authorization attribute to it
      $headers = @{ Authorization = "Basic $encodedCredentials" }
      write-host "0"
      # Step 4. Make the GET request
      $responseData = Invoke-WebRequest -Uri http://35.170.71.8:9000/api/project_badges/quality_gate?project=java-project_java-project -Method Get -Headers $headers -UseBasicParsing
      $x = $responseData.content | ConvertTo-Json | write-host
      
      write-host $x.projectStatus.status
      write-host "1"
      $sonarQualityGateResult = $x.projectStatus.status
      write-host $sonarQualityGateResult
      
      if($sonarQualityGateResult -eq 'SONARQUBE QUALITY GATE FAIL'){
      write-host "CI failed due to Sonarqube quality Gate"
      }
      else
      {
        write-host "CI success"
      }
    


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $token = [System.Text.Encoding]::UTF8.GetBytes($env:SonarToken + ":")
      Write-Output "ENV Token value:  "+ $token
      $token1 = [System.Text.Encoding]::UTF8.GetBytes($SonarToken + ":")
      Write-Output "with out ENV Token Value :  "+ $token1

      $base64 = [System.Convert]::ToBase64String($token)
      Write-Host $token
      Write-Host $base64
      $basicAuth = [string]::Format("Basic {0}", $base64)
      $headers = @{ Authorization = $basicAuth }
      Write-Host $headers
      $result = Invoke-RestMethod -Method Get -Uri http://35.170.71.8:9000/dashboard?id=java-project_java-project -Headers $headers -UseBasicParsing
      $result | ConvertTo-Json | Write-Host

      
      if ($result.projectStatus.status -eq "OK") {
      Write-Host "Quality Gate Succeeded"
      #errorActionPreference: 'continue'
      }
      else
      {
        Write-Host "Quality Gate Fails"
        #errorActionPreference: 'stop'
      }
    
    #errorActionPreference: 'continue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $branch = "$(Build.SourceBranch)"
      $branch = $branch -replace 'refs\/heads\/',''
                
      cmd.exe /c  $env:CMDPATH $env:REPO $branch
               
      Write-Host "first"
      $branch = $branch -replace '\/','-'
      Write-Host $branch
      $json=Get-Content $env:JSONPATH\$branch.json | ConvertFrom-Json
      Write-Host "second"
      Write-Host $json.projectStatus.status
      if ($json.projectStatus.status -eq "OK") {
      Write-Host "Quality Gate Succeeded"
      }else{
      throw "Quality gate failed"
      }